# Generated by Django 4.2.2 on 2023-06-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0002_videoblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='number_blocks')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
