# Generated by Django 4.2.2 on 2023-06-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0005_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download',
            name='link',
        ),
        migrations.RemoveField(
            model_name='download',
            name='name',
        ),
        migrations.AddField(
            model_name='download',
            name='imglink',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='download',
            name='imgname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='download',
            name='pdflink',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='download',
            name='pdfname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
