# Generated by Django 4.2.2 on 2023-06-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0007_rename_imgname_download_name_remove_download_imglink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
