# Generated by Django 4.2.2 on 2023-06-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0008_blogpost_description_alter_blogpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
