# Generated by Django 4.2.2 on 2023-06-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0009_alter_blogpost_author_alter_blogpost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
    ]
